# Copyright The Linux Foundation and each contributor to LFX.
---
site_name: 'LFX One Access Check'
site_description: 'Documentation for LFX One Access Check'
nav:
  - Home: index.md
plugins:
  - techdocs-core
